const data = [
  {
    name: "Man T-shirt",
    price: 30,
    currency: "$",
    photo: "/images/tshirt-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    name: "Man drees",
    price: 80,
    currency: "$",
    photo: "/images/dress-shirt-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    name: "computer core-i9",
    price: 180,
    currency: "$",
    photo: "/images/computer-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    name: "mobile galaxy",
    price: 70,
    currency: "$",
    photo: "/images/mobile-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    name: "laptop-img.png",
    price: 90,
    currency: "$",
    photo: "/images/laptop-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    name: "necklace",
    price: 90,
    currency: "$",
    photo: "/images/neklesh-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    name: "kangan",
    price: 90,
    currency: "$",
    photo: "/images/kangan-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
];
export default data;
