import { LuFolderMinus } from "react-icons/lu";

const data = [
  {
    id: 13,
    name: "Man T-shirt",
    price: 30,
    currency: "$",
    photo: "/images/tshirt-img2.png",
    detailPhotos: [
      "/images/tshirt-img2.png",
      "/images/download-removebg-preview.png",
      "/images/png-clipart-printed-t-shirt-polo-shirt-clothing-t-shirt-tshirt-fashion-thumbnail-removebg-preview.png",
    ],
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 14,
    name: "Man drees",
    price: 80,
    currency: "$",
    photo: "/images/dress-shirt-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 15,

    name: "computer core-i9",
    price: 180,
    currency: "$",
    photo: "/images/computer-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 16,

    name: "mobile galaxy",
    price: 70,
    currency: "$",
    photo: "/images/mobile-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 17,

    name: "laptop-img.png",
    price: 90,
    currency: "$",
    photo: "/images/laptop-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 18,

    name: "necklace",
    price: 90,
    currency: "$",
    photo: "/images/neklesh-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 19,

    name: "kangan",
    price: 90,
    currency: "$",
    photo: "/images/kangan-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 20,

    name: "Man T-shirt",
    price: 30,
    currency: "$",
    photo: "/images/tshirt-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 21,
    name: "Man drees",
    price: 80,
    currency: "$",
    photo: "/images/dress-shirt-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 22,
    name: "computer core-i9",
    price: 180,
    currency: "$",
    photo: "/images/computer-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 23,
    name: "mobile galaxy",
    price: 70,
    currency: "$",
    photo: "/images/mobile-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 24,
    name: "laptop-img.png",
    price: 90,
    currency: "$",
    photo: "/images/laptop-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 25,
    name: "necklace",
    price: 90,
    currency: "$",
    photo: "/images/neklesh-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 26,
    name: "kangan",
    price: 90,
    currency: "$",
    photo: "/images/kangan-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 27,
    name: "Man T-shirt",
    price: 30,
    currency: "$",
    photo: "/images/tshirt-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 28,
    name: "Man drees",
    price: 80,
    currency: "$",
    photo: "/images/dress-shirt-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 29,
    name: "computer core-i9",
    price: 180,
    currency: "$",
    photo: "/images/computer-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 30,
    name: "mobile galaxy",
    price: 70,
    currency: "$",
    photo: "/images/mobile-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 31,
    name: "laptop-img.png",
    price: 90,
    currency: "$",
    photo: "/images/laptop-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 32,
    name: "necklace",
    price: 90,
    currency: "$",
    photo: "/images/neklesh-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 33,
    name: "kangan",
    price: 90,
    currency: "$",
    photo: "/images/kangan-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 34,
    name: "Man T-shirt",
    price: 30,
    currency: "$",
    photo: "/images/tshirt-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 35,
    name: "Man drees",
    price: 80,
    currency: "$",
    photo: "/images/dress-shirt-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 36,
    name: "computer core-i9",
    price: 180,
    currency: "$",
    photo: "/images/computer-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 37,
    name: "mobile galaxy",
    price: 70,
    currency: "$",
    photo: "/images/mobile-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 38,
    name: "laptop-img.png",
    price: 90,
    currency: "$",
    photo: "/images/laptop-img.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 39,
    name: "necklace",
    price: 90,
    currency: "$",
    photo: "/images/neklesh-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
  {
    id: 40,
    name: "kangan",
    price: 90,
    currency: "$",
    photo: "/images/kangan-img2.png",
    shortDescription: "This is a short description of the product.",
    reviews: [{ name: "Abdelrahman Maged", rate: 4.5, createdAt: Date.now() }],
  },
];

export default data.map((el) => {
  return {
    id: el.id,
    name: el.name,
    price: el.price,
    currency: el.currency,
    photo: el.photo,
    detailPhotos: el.detailPhotos || [el.photo, el.photo, el.photo],
    avgRating: Math.trunc(Math.random() * 40 + 10) / 10,
    shortDescription: el.shortDescription,
    stock: Math.trunc(Math.random() * 250 + 10),
    reviews: el.reviews,
    longDescription:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et molestias dolorum voluptatum quasi consequuntur, omnis libero laudantium ipsam adipisci, eligendi recusandae earum sapiente. Necessitatibus eaque cum provident fugit nostrum accusamus laudantium, fuga ab, suscipit optio, iure minima non molestiae veritatis nam fugiat eos officia. Quisquam ratione, dolores doloribus modi explicabo voluptatum asperiores unde ab doloremque cupiditate impedit, distinctio, nobis aperiam illo perferendis a? Praesentium voluptatum voluptates facilis vitae. Ab maxime recusandae fuga impedit reprehenderit ullam magni doloremque dolorem suscipit. Blanditiis reiciendis animi, illo, dolores sint necessitatibus nihil architecto deserunt quasi cupiditate consequuntur. Repellat cumque minima deleniti culpa ipsum beatae obcaecati consectetur suscipit magni dolore distinctio quis officia vel sed modi ipsa tenetur quisquam commodi, eligendi minus? Aut nobis quaerat ratione.",
  };
});
